apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-app-config
  namespace: {{ .Release.Namespace }}
data:
  S3_BUCKET: scale-etl-bucket-1
  MODEL_KEY: models/duel_model.pkl
  AWS_REGION: eu-west-1