apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-app-ui
  labels:
    app.kubernetes.io/name: scale-app
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: scale-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scale-app
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: scale-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scale-app
        app.kubernetes.io/component: ui
        app.kubernetes.io/instance: scale-app
    spec:
      serviceAccountName: scale-app-ecr-sa
      containers:
        - name: scale-app-ui
          image: "018535004264.dkr.ecr.eu-west-1.amazonaws.com/scale:ui-latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      automountServiceAccountToken: true