apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "..apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "..apiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "..s3serviceAccountName" . }}
      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket | quote }}
            - name: MODEL_KEY
              value: {{ .Values.s3.modelKey | quote }}
            - name: AWS_REGION
              value: {{ .Values.s3.region | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      securityContext:
        fsGroup: 1000
      {{- if .Values.s3serviceAccount.create }}
      automountServiceAccountToken: {{ .Values.s3serviceAccount.automount }}
      {{- end }}
