apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..uiselectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..uiselectorLabels" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "..ecrserviceAccountName" . }}
      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.uiImage.uiRepository }}:{{ .Values.uiImage.uiTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      {{- if .Values.esoserviceAccount.create }}
      automountServiceAccountToken: true
      {{- end }}
