apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-app-ui
  labels:
    app.kubernetes.io/name: scale-app
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: scale-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scale-app
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: scale-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scale-app
        app.kubernetes.io/component: ui
        app.kubernetes.io/instance: scale-app
    spec:
      serviceAccountName: {{ include "..ecrserviceAccountName" . }}
      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.uiImage.uiRepository }}:{{ .Values.uiImage.uiTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      {{- if .Values.esoserviceAccount.create }}
      automountServiceAccountToken: true
      {{- end }}