apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-api
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "..s3serviceAccountName" . }}

      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: S3_BUCKET
              value: "scale-etl-bucket-1"
            - name: MODEL_KEY
              value: "models/duel_model.pkl"
            - name: AWS_REGION
              value: "eu-west-1"

          # ---- Probes ----
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.port }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.port }}
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          #   failureThreshold: 6
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      securityContext:
        fsGroup: 1000

      {{- if .Values.s3serviceAccount.create }}
      automountServiceAccountToken: {{ .Values.s3serviceAccount.automount }}
      {{- end }}
