apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-api
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..selectorLabels" . | nindent 6 }}
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: {{ include "..s3serviceAccountName" . }}
      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: S3_BUCKET
              value: "scale-etl-bucket-1"
            - name: MODEL_KEY
              value: "models/duel_model.pkl"
            - name: AWS_REGION
              value: "eu-west-1"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      securityContext:
        fsGroup: 1000
      {{- if .Values.s3serviceAccount.create }}
      automountServiceAccountToken: {{ .Values.s3serviceAccount.automount }}
      {{- end }}