apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: {{ include "..ecrserviceAccountName" . }}
      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.uiImage.uiRepository }}:{{ .Values.uiImage.uiTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      {{- if .Values.esoserviceAccount.create }}
      automountServiceAccountToken: true
      {{- end }}
