apiVersion: v1
kind: Service
metadata:
  name: scale-app-svc
spec:
  selector:
    app.kubernetes.io/name: scale-app
    app.kubernetes.io/instance: scale-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
