apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "..fullname" . }}-ingress-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuer.name }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx

spec:
  ingressClassName: {{ .Values.certManager.uiCertificate.ingressClassName }}
  tls:
    - hosts:
{{- range .Values.certManager.uiCertificate.dnsNames }}
        - {{ . }}
{{- end }}
      secretName: {{ .Values.certManager.uiCertificate.secretName }}
  rules:
{{- range .Values.certManager.uiCertificate.dnsNames }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "..fullname" $ }}-service-ui
                port:
                  number: 80
{{- end }}