apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "..fullname" . }}-ingress-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuer.name }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "100"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "60"

spec:
  ingressClassName: {{ .Values.certManager.uiCertificate.ingressClassName }}
  tls:
    - hosts:
{{- range .Values.certManager.uiCertificate.dnsNames }}
        - {{ . }}
{{- end }}
      secretName: {{ .Values.certManager.uiCertificate.secretName }}
  rules:
{{- range .Values.certManager.uiCertificate.dnsNames }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "..fullname" $ }}-service-ui
                port:
                  number: 80
{{- end }}