apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "..fullname" . }}-ingress-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuer.name }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "100"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "60"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      gzip on;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
      gzip_min_length 1000;
      add_header X-Cache-Status $upstream_cache_status;
      add_header X-Response-Time $request_time;

spec:
  ingressClassName: {{ .Values.certManager.uiCertificate.ingressClassName }}
  tls:
    - hosts:
{{- range .Values.certManager.uiCertificate.dnsNames }}
        - {{ . }}
{{- end }}
      secretName: {{ .Values.certManager.uiCertificate.secretName }}
  rules:
{{- range .Values.certManager.uiCertificate.dnsNames }}
    - host: {{ . }}
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "..fullname" $ }}-service-ui
                port:
                  number: 80
{{- end }}