apiVersion: v1
kind: Service
metadata:
  name: wakanda-duel-svc
spec:
  selector:
    app: wakanda-duel
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}